### ISSUE TITLE
`kustomize overlay/accesskey` returns error due to mismatched apiversion

### ISSUE THREAD

**Issue by regorsmitz** [e2fyi/kubeflow-aws#13]
When I run:

`kubectl kustomize overlay/accesskey`
I get:
Error: failed to find an object with apps_v1beta2_Deployment|ml-pipeline-ui to apply the patch

I was able to fix this problem by updating the ml-pipieline-ui and ml-pipeline definitions in `accesskey/aws-configurations-patch.yaml` to use apiVersion `apps/v1`.

**Comment by eterna2** [comment]
Thanks for the catch. We are not using the access key manifest as it is less secure than the IAM version, hence we missed this when the base manifest is updated. I will make a PR to fix this.
